name: Job Alert Bot

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:        # Allow manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Update OpenSSL
        run: sudo apt-get update && sudo apt-get install --only-upgrade openssl

      - name: Install CA certificates
        run: sudo apt-get update && sudo apt-get install -y ca-certificates

      - name: Run Job Alert Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python main.py