name: Job Alert Bot

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download previous jobs.db
        uses: actions/download-artifact@v4  # ✅ Updated to v4
        with:
          name: jobs-db
          path: storage
        continue-on-error: true

      - name: Run Job Alert Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Upload updated jobs.db
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: jobs-db
          path: storage/jobs.db
