name: Job Alert Bot

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright browsers
        run: python -m playwright install --with-deps


      - name: Download previous jobs.db from artifacts branch
        run: |
          mkdir -p storage
          git fetch origin artifacts
          git show origin/artifacts:storage/jobs.db > storage/jobs.db || echo "No previous DB"

      - name: Run Job Alert Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Commit updated jobs.db to artifacts branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin artifacts
          git checkout -B artifacts origin/artifacts || git checkout --orphan artifacts
          git add storage/jobs.db
          git commit -m "Update jobs.db" || echo "No changes to commit"
          git push origin artifacts
